server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jjzone?serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyl.entity
logging:
  level:
    org.springframework.security: debug

